[package]
name = "cmus-lyrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpris = "1.1.2"
tui = "0.18.0"
crossterm = "0.23.2"
lyricrustacean = "0.1.0"